
name: CI

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      run: | 
          python -m pip install --upgrade pip
          pip install fastapi pytest opencv-python numpy tensorflow aiofiles uvicorn
    - name: Run tests
      run: |
        pytest